# Generated by Django 5.0.6 on 2024-05-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='GroupAdmin',
        ),
    ]
