# Generated by Django 5.0.6 on 2024-05-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_admin_groupadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='owner',
            new_name='user',
        ),
    ]
