# Generated by Django 5.0.6 on 2024-05-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_groupchat_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Member',
        ),
    ]
